#!/usr/bin/env bash
# fizz=%3, buzz=%5, fizzbuss=%15 - from 1 to 100
for i in {1..100}
do
	if (( i % 15 == 0 ))
	then 
		echo "FizzBuzz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	((i++))
done
