#!/usr/bin/env bash
# prints bad luck, good luck , and Best School at 4, 8, and other interations
i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]
		then echo "bad luck"
	elif [ $i = 8 ]
		then echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
